source 'https://rubygems.org'

#git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'inifile'
gem 'json'
gem 'optparse'
gem 'rb-inotify'
gem 'rmagick'
gem 'dotenv'
gem 'systemu'
