# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
#gem 'optparse'
gem 'rb-inotify'
gem 'json'
gem 'rmagick'
gem 'inifile'
gem 'rubocop'